### ISSUE TITLE
Conda dependency conflicts

### ISSUE THREAD

**Issue by dnbenso** [aknijn/eurl_vtec_wgs_pt-galaxy#1]
Hi 
I am having trouble installing the dependencies via conda for this tool.   Do you have a specific set of conda versions and builds that you know work?  Currently I'm just going with the requirements in the tool file.  
After Galaxy failed to install the dependencies I'm attempting to create the conda environment manually. 
Thanks in advance for an insights you can give.
Cheers
Derek

**Comment by aknijn** [comment]
Hello
This is a problem that occurs with conda, dependencies that worked at a certain moment, stop working. Could you specify what problem you are having. I am aware of a problem that still occurs related to the installation of MentaLiST on which I opened an issue some time ago (https://github.com/WGS-TB/MentaLiST/issues/112). If you are having the same problem then I could substitute MentaLiST with the package MLST (https://github.com/tseemann/mlst) which installs without problems and obtain the same results.
Bye, Arnold

**Comment by dnbenso** [comment]
Thank you so much for your response.  Yes, MentaLiST requires julia which has a conflict ... or .. exercises a bug in libgit2 which makes the conda install fail.
I can change MentaLiST out for MLST if this works. 
I'm wanting to use your pipeline to validate another galaxy pipeline that I am using for shiga toxin typing in e.coli isolates.
I'm happy to acknowledge this project if any publications come from this.

**Comment by aknijn** [comment]
Ok, I will do the substitution then. If you are specifically interested in the shiga toxin typing you could try that part of the pipeline without the other typing tools, you can find it here: https://github.com/aknijn/shigatoxin-galaxy

**Comment by aknijn** [comment]
The package is updated now and should install without problems.

**Comment by dnbenso** [comment]
Hi Aknijn

Thanks so  much for your help on this.

Kind regards
Derek

**Comment by aknijn** [comment]
Hello Derek
You are welcome. Let me know how the validation went.
Best, Arnold

**Comment by aknijn** [comment]
I just became aware that SPAdes 3.14.1 did not work with the code while version 3.14.0 did. The code has now been updated to wok well with both.
